feat!: turn MISSING into a more proper sentinel
interactions-py/interactions.py pull request #1007
Opened 2022-08-07 03:18 UTC by Catalyst4222

## About

This pull request converts MISSING into a class instance, which allows for things like `__repr__`, `__bool__`, and other similar things to be added

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

2022-08-07 03:21 UTC, Astrea49 commented on interactions/api/models/attrs_utils.py
> +    """A pseudosentinel based from an empty object. This is now more compliant with PEP"""
This is now a proper sentinel, not a pseudosentinel.

2022-08-12 23:15 UTC, EdVraz requested changes
I don't think this is breaking?

Also isn't this more a refactor than a feat? It doesn't essentially add new features

2022-08-20 08:16 UTC, EdVraz commented
Marked this as not breaking since it doesn't affect the end user's code

2022-08-20 08:17 UTC, EdVraz approved these changes

2022-08-20 08:17 UTC, merged