refactor: make Command.dispatch a function
interactions-py/interactions.py pull request #1040
Opened 2022-08-26 16:43 UTC by Catalyst4222

## About

This pull request changes Command.dispatch from a property into a function
This is mostly just to make it easier to override in exts, though it does help to simplify the code

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

2022-08-26 23:51 UTC, Toricane requested changes
Please update the docstring

2022-08-26 23:51 UTC, Toricane commented on interactions/client/models/command.py
> +    async def dispatcher(
Update the docstring

2022-08-27 15:34 UTC, Catalyst4222 commented on interactions/client/models/command.py
> +    async def dispatcher(
Done

2022-08-28 15:27 UTC, Toricane requested changes
More changes required

2022-08-28 15:27 UTC, Toricane commented on interactions/client/models/command.py
>          """
Add period at end of the function description sentence.
Make the opening quotes `r"""`.
Turn `args` into `\*args`.
Turn `kwargs` into `\**kwargs`.
Add `:type \*args: Tuple[Any]`
Add `:type \**kwargs: Dict[Any]`
Add descriptions for `:rtype:` and `:return:`.

2022-08-30 05:04 UTC, Catalyst4222 commented on interactions/client/models/command.py
>          """
Args shouldn't be typehinted as a tuple, that would imply each argument in it is a tuple

2022-08-31 01:09 UTC, Toricane commented on interactions/client/models/command.py
>          """
There are no examples of documentation of args that I can point towards, but there are examples of kwargs being typehinted as dict in the docstrings, such as the ones in bot.py, so I think args should be tuple

2022-09-01 02:35 UTC, Catalyst4222 commented on interactions/client/models/command.py
>          """
The typehint following `*args` is what's inside the tuple

Here the typehints are for a tuple (python 3.10, same case for earlier versions)
![image](https://user-images.githubusercontent.com/84055084/187819803-d62cc48e-79b4-4718-afab-f6f8069a05d1.png)

If it's set to only `int`, then the typehints for each item in `args` is for ints
![image](https://user-images.githubusercontent.com/84055084/187820083-626453c5-4a0b-442e-bf17-252a0caad289.png)

2022-09-01 03:33 UTC, Toricane commented on interactions/client/models/command.py
>          """
> but there are examples of kwargs being typehinted as dict in the docstrings, such as the ones in bot.py, so I think args should be tuple

I'm not talking about typehints in the function parameters, I'm talking about the docstring. Maybe the types on the docstrings can be changed in a separate PR since they're all over the place.

2022-09-01 03:50 UTC, Catalyst4222 commented on interactions/client/models/command.py
>          """
The types in docstrings should match the function parameters. For now, I'll match the docstring to the rest of the library, but cleaning up docstring parameters is needed at some point

2022-09-04 04:28 UTC, Toricane approved these changes
LGTM!

2022-09-04 04:46 UTC, merged