refactor: Change type of parameters in scheduled event requests from Snowflake to int
interactions-py/interactions.py pull request #1067
Opened 2022-09-03 11:46 UTC by Nanrech

## About

This pull request refactors the scheduledEvent http methods to take in `int` objects instead of `Snowflake`.
There's also a fix for `get_scheduled_events`, so the method now works properly when the parameter `with_counts` is set to True.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [x] Bugfix

2022-09-04 04:32 UTC, Toricane requested changes
Please modify the docstrings, mainly changing parameter descriptions and adding parameter types

2022-09-04 09:59 UTC, Nanrech commented
> Please modify the docstrings, mainly changing parameter descriptions and adding parameter types

Their current state is identical to other docstrings in the http directory, though. What changes do you suggest?

2022-09-05 15:15 UTC, Toricane commented
They still say they are snowflakes, and the `:type X: ...` is missing for them as well

2022-09-05 16:03 UTC, Damego commented
In other http files same thing

2022-09-05 19:08 UTC, Nanrech commented
> They still say they are snowflakes, and the `:type X: ...` is missing for them as well

That happens to be the same across ALL http files. If we really want that changed, we should do so in a separate PR addressing all those files.

2022-09-05 19:08 UTC, Toricane commented
Oh ok, thanks for clarifying

2022-09-05 19:09 UTC, Toricane approved these changes
LGTM!

2022-09-05 19:09 UTC, merged