feat: implement forum helpers
interactions-py/interactions.py pull request #1087
Opened 2022-09-16 18:19 UTC by EdVraz

## About

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [ ] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [x] For the documentation
  - [x] To add a new feature
  - [x] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-09-16 18:19 UTC, EdVraz commented
shit forgot docs

2022-09-16 18:27 UTC, EdVraz commented
done.

2022-09-20 04:53 UTC, Toricane requested changes
A suggestion

2022-09-20 04:53 UTC, Toricane commented on interactions/api/error.py
> +            14: "Fatal conflict between object and attempted action (cannot run this action on current object).",
I don't think having both of those descriptions is good, maybe put one of them?

2022-09-20 23:33 UTC, Toricane approved these changes
LGTM!

2022-09-20 23:33 UTC, merged