feat: Add support for `REQUEST_MEMBERS` packet sending
interactions-py/interactions.py pull request #1089
Opened 2022-09-18 12:29 UTC by Damego

## About

This pull request implements support for `REQUEST_MEMBERS` packet sending and `GUILD_MEMBERS_CHUNK` event receiving

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [x] For the documentation
  - [x] To add a new feature
  - [x] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-09-20 04:34 UTC, Toricane requested changes
Small refactor

2022-09-20 04:34 UTC, Toricane commented on interactions/api/gateway/client.py
> +                                iterable.append(_obj)
```suggestion
            elif ids is not None:
                objs = getattr(obj, attr, None)
                if "_update" in name:
                    if objs is not None:
                        iterable.clear()
                        iterable.extend(objs)
                elif "_chunk" in name:
                    if objs is not None:
                        for _obj in objs:
                            for index, __obj in enumerate(iterable):
                                if __obj.id == _obj.id:
                                    iterable[index] = _obj
                                    break
                            else:
                                iterable.append(_obj)
```

2022-09-20 23:32 UTC, Toricane requested changes
One more thing

2022-09-20 23:32 UTC, Toricane commented on interactions/api/gateway/client.py
> +                                iterable.append(_obj)
```suggestion
                if objs is not None:
                    if "_update" in name:
                        iterable.clear()
                        iterable.extend(objs)
                    elif "_chunk" in name:
                        for _obj in objs:
                            for index, __obj in enumerate(iterable):
                                if __obj.id == _obj.id:
                                    iterable[index] = _obj
                                    break
                            else:
                                iterable.append(_obj)
```

2022-09-21 04:14 UTC, Damego commented on interactions/api/gateway/client.py
> +                                iterable.append(_obj)
Can you use walrus operator to get ‘objs‘ in if statement above

2022-09-22 23:53 UTC, Toricane approved these changes
LGTM!

2022-09-22 23:53 UTC, merged