feat: exclude existing guild from on_guild_create event after starting
interactions-py/interactions.py pull request #1104
Opened 2022-09-26 07:27 UTC by ItsRqtl

## About

This pull request is about on_guild_create event, which save the guilds array from ready (start) event, then excluding them from dispatching (then remove them from the list so the event will dispatch if the bot rejoined).

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [x] To add a new feature
  - [ ] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-09-26 08:23 UTC, Damego commented
Will be better implement new event `guild_join` instead of limiting `guild_create`

2022-09-26 08:39 UTC, ItsRqtl commented
reverted guild_create, dispatching new guild_join instead

2022-09-26 15:01 UTC, Damego requested changes

2022-09-26 15:01 UTC, Damego commented on interactions/api/gateway/client.py
> +                self.__start_guild = [i["id"] for i in data["guilds"]]
`READY` event can be dispatched multiply times during runtime and every time it will contain a list with guilds. SO after a second `READY` event you will get `guild_join` event dispatching for all your guilds. I suggest move this from if statement.
Also rename `__start_guild` to `__unavailable_guilds`

2022-09-26 15:01 UTC, Damego commented on interactions/api/gateway/client.py
> +                            self.__start_guild.remove(str(id))
rename `__start_guild` to `__unavailable_guilds`

2022-09-29 16:19 UTC, Damego approved these changes

2022-10-29 17:39 UTC, Catalyst4222 approved these changes

2022-10-29 17:40 UTC, merged