refactor: use `attrs.asdict` as a way to get json data of the object
interactions-py/interactions.py pull request #1126
Opened 2022-10-17 16:00 UTC by Damego

## About

This pull request...(will write soon).
Draft until yes

## Checklist

- [ ] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [ ] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [ ] To add a new feature
  - [x] As a general enhancement
  - [x] As a refactor of the library/the library's code
  - [x] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-10-19 08:21 UTC, Damego commented
Ready for review. Any tests appreciated

2022-10-19 12:30 UTC, sillyElvy commented
Do not merge for another few days as this is a major change

2022-10-19 12:31 UTC, EdVraz requested changes
> Optimized code in some places: using walrus operators and objects instead of dicts(wsclient).


Out of the scope of this PR, please remove

2022-10-19 12:33 UTC, Damego commented
> > Optimized code in some places: using walrus operators and objects instead of dicts(wsclient).
> 
> Out of the scope of this PR, please remove

Remove changes or just these words?

2022-10-19 12:33 UTC, EdVraz commented
> > > Optimized code in some places: using walrus operators and objects instead of dicts(wsclient).
> > 
> > Out of the scope of this PR, please remove
> 
> Remove changes or just these words?

The changes

2022-10-19 12:49 UTC, Damego commented
uhh. It can't be fully reverted because someone previously added [object into json](https://github.com/interactions-py/library/pull/1126/files#diff-9c1dc218ce0d42c712c5591f6797cead2f2b2084810fb6d9f66dd48bf1c112ebL373) but we can't do it anymore and that's why i refactored `__sub_command_context` function.

2022-10-19 12:53 UTC, EdVraz commented
> uhh. It can't be fully reverted because someone previously added [object into json](https://github.com/interactions-py/library/pull/1126/files#diff-9c1dc218ce0d42c712c5591f6797cead2f2b2084810fb6d9f66dd48bf1c112ebL373) but we can't do it anymore and that's why i refactored `__sub_command_context` function.

It sounded like a random change, if it is only _json related it's ok

2022-10-19 12:56 UTC, Damego commented
also using _json property few times in one funtion is a bad. It will everytime call `asdict`. Yeah its takes just 1-2 milliseconds but still

2022-10-19 13:01 UTC, EdVraz commented
Yeah

2022-10-19 13:04 UTC, Damego commented
> Yeah

So remove these changes(using walrus operator)?

2022-10-19 13:09 UTC, EdVraz commented
> > Yeah
> 
> So remove these changes(using walrus operator)?

If you did the changes while removing the _json it can stay.

2022-10-28 15:01 UTC, Damego commented
Draft until #1132 is merged because 
> ... this is a major change

xD

2022-11-06 17:14 UTC, Damego commented on interactions/utils/attrs_utils.py
> +                return str(value)
```suggestion
                return int(value)
```

2022-11-06 18:04 UTC, EdVraz requested changes

2022-11-06 18:04 UTC, sillyElvy commented on interactions/api/gateway/client.py
> -                                else:
IN the upper part you are doing the check, In the lower part you removed it. why?

2022-11-06 18:04 UTC, sillyElvy commented on interactions/client/models/component.py
>      def new(cls, *components: Union[Button, SelectMenu, TextInput]) -> "ActionRow":
```suggestion
    def new(cls, *components: Union[Button, SelectMenu, TextInput]) -> List["ActionRow"]:
```

If you change the method you can fix the rtype aswell

2022-11-06 18:04 UTC, sillyElvy commented on interactions/client/models/component.py
> +                                or component_json.get("url")
```suggestion
```

Include it and let it error, it produces less confusion than just to let it out

2022-11-06 18:04 UTC, sillyElvy commented on interactions/client/models/component.py
> +                    or component_json.get("url")
```suggestion
```

2022-11-06 18:04 UTC, sillyElvy commented on interactions/client/models/component.py
> +                            or component_json.get("url")
```suggestion
```

2022-11-06 18:04 UTC, sillyElvy commented on interactions/client/models/component.py
> +                or component_json.get("url")
```suggestion
```

2022-11-06 18:04 UTC, EdVraz commented on interactions/utils/attrs_utils.py
> +                return int(value)
Snowflakes are technically strings

2022-11-06 18:04 UTC, EdVraz commented on interactions/api/gateway/client.py
> -                                else:
WAIT NVM IM STUPID

2022-11-07 12:58 UTC, EdVraz commented on interactions/api/gateway/client.py
> +                                option.value = _type[option.value]
It should assign the resolved object to `option.value` so that it is not the ID of the object, if I'm reading it correctly

2022-11-07 13:07 UTC, Damego commented on interactions/api/gateway/client.py
> +                                option.value = _type[option.value]
yeah, you're right. I removed that comment

2022-11-10 12:30 UTC, EdVraz commented
Also merge conflicts

2022-11-10 12:38 UTC, Damego commented
Resolved

2022-11-18 12:54 UTC, mAxYoLo01 commented
Tested PR and works on my end, LGTM!

2022-11-23 18:14 UTC, EdVraz approved these changes
Since the other devs don't seem interested in having a look at this PR I'm approving it

2022-11-23 18:16 UTC, merged