feat: Implement testing
interactions-py/interactions.py pull request #1132
Opened 2022-10-21 20:20 UTC by EdVraz

## About

This pull request implements testing by creating objects and checking if the generated payloads are equal to the previously checked and correct payloads.

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [ ] To add a new feature
  - [x] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [x] To finally resolve ä497

This is:
  - [ ] A breaking change

2022-10-21 21:00 UTC, Toricane requested changes
Some suggestions

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
```suggestion
    assert command.full_data == dict(
        default_member_permissions="2147483648",
        description="Hello!",
        description_localizations={},
        dm_permission=True,
        name="command",
        name_localizations={},
        options=[],
        type=1,
    )
```
Looks nicer imo

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
```suggestion
        "hi", name="hi", type=interactions.OptionType.USER, required=True
```
Connector is automatically set as parameter name if name= is specified

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:00 UTC, Toricane commented on tests/test_new_command_system.py
> +    }
https://github.com/interactions-py/library/pull/1132#discussion_r1002181715

2022-10-21 21:01 UTC, EdVraz commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
Oh cool then I have to make two test cases for it xD

2022-10-21 21:05 UTC, Toricane commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
Oh yeah btw required= is automatic too based on whether there is a default for the parameter

2022-10-21 21:06 UTC, EdVraz commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
If you looked at the function names you'd know 😅

I'm checking if the overriding works

If any of the checks fails then something is not ok

2022-10-22 08:52 UTC, EdVraz commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
> Connector is automatically set as parameter name if name= is specified

uhh.. yeah so about that:
```py
============================================================================================================== FAILURES =============================================================================================================== 
___________________________________________________________________________________ test_basic_command_with_connector_option_with_read_from_kwargs ____________________________________________________________________________________ 

fake_client = <interactions.client.bot.Client object at 0x0000022169ADECE0>

    def test_basic_command_with_connector_option_with_read_from_kwargs(fake_client):
        @fake_client.command()
        @interactions.option("hi", name="hi")
        async def command(ctx, d: interactions.Member):
            """Hello!"""

>       assert command.full_data == dict(
            default_member_permissions="2147483648",
            description="Hello!",
            description_localizations={},
            dm_permission=True,
            name="command",
            name_localizations={},
            options=[
                {
                    "connector": "d",
                    "description": "hi",
                    "name": "hi",
                    "required": True,
                    "type": interactions.OptionType.USER,
                }
            ],
            type=1,
        )
E       AssertionError: assert {'default_mem...n': True, ...} == {'default_mem...n': True, ...}
E         Omitting 7 identical items, use -vv to show
E         Differing items:
E         {'options': [{'description': 'hi', 'name': 'hi', 'required': True, 'type': <OptionType.USER: 6>}]} != {'options': [{'connector': 'd', 'description': 'hi', 'name': 'hi', 'required': True, ...}]}
E         Use -v to get more diff

tests\test_new_command_system.py:131: AssertionError
======================================================================================================= short test summary info ======================================================================================================= 
FAILED tests/test_new_command_system.py::test_basic_command_with_connector_option_with_read_from_kwargs - AssertionError: assert {'default_mem...n': True, ...} == {'default_mem...n': True, ...}
```

2022-10-22 09:12 UTC, EdVraz commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
oh I see how you did it, this is interesting

2022-10-22 14:21 UTC, Toricane commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
Wait what happened

2022-10-22 14:23 UTC, EdVraz commented on tests/test_new_command_system.py
> +        "hi", name="hi", type=interactions.OptionType.USER, required=True, connector="d"
Well the "connector" is shown in the option dict (check code above) if its put inside the option decorator but not if its made automatically and I thought that was a bug but command.connectors still is correct

2022-10-23 20:47 UTC, Toricane requested changes
So much unnecessary code

2022-10-23 20:47 UTC, Toricane commented on tests/test_library_exception.py
> +)
```suggestion
codes = (
    *range(15),
    400,
    401,
    *range(403, 406),
    429,
    502,
    *range(4000, 4015),
    *range(10001, 10017),
    10020,
    *range(10026, 10034),
    10036,
    10038,
    10049,
    10050,
    10057,
    10059,
    10060,
    10062,
    10063,
    *range(10065, 10072),
    10087,
    20001,
    20002,
    20009,
    20012,
    20016,
    20018,
    20022,
    20024,
    20028,
    20029,
    20031,
    20035,
    *range(30001, 30006),
    30007,
    30008,
    30010,
    30013,
    30015,
    30016,
    30018,
    30019,
    *range(30030, 30036),
    *range(30037, 30041),
    30042,
    30046,
    30047,
    30048,
    30052,
    *range(40001, 40008),
    40012,
    40032,
    40033,
    40041,
    40043,
    40060,
    40061,
    *range(50001, 50018),
    *range(50019, 50022),
    *range(50024, 50029),
    *range(50033, 50037),
    50041,
    50045,
    50046,
    50054,
    50055,
    50068,
    50070,
    50074,
    50080,
    50081,
    *range(50083, 50087),
    50095,
    50097,
    50101,
    50109,
    50132,
    50138,
    50146,
    50600,
    60003,
    80004,
    90001,
    110001,
    130000,
    150006,
    160002,
    *range(160004, 160008),
    *range(170001, 170008),
    180000,
    180002,
    200000,
    200001,
    220003,
)
```
i spent way too long on this

2022-10-23 20:47 UTC, Toricane commented on tests/test_library_exception.py
> +}
```suggestion
__error = dict(
    _errors=[
        dict(
            code="BASE_TYPE_REQUIRED",
            message="This field is required",
        )
    ]
)
data = dict(
    code=50035,
    errors=dict(
        components={
            "0": dict(
                components={
                    **{str(i): __error for i in range(10)},
                    **{str(i): __error for i in range(10, 74)},
                }
            )
        }
    ),
    message="Invalid Form Body",
)
```

2022-10-23 20:47 UTC, Toricane commented on tests/test_new_command_system.py
> +            {
Convert all inner dicts to `dict()`?

2022-10-23 20:47 UTC, EdVraz commented on tests/test_library_exception.py
> +)
XD

2022-10-23 20:49 UTC, Toricane commented on tests/test_library_exception.py
> +)
can you commit this again? i removed some underscores

2022-10-23 20:50 UTC, Toricane commented on tests/test_library_exception.py
> +)
@EdVraz

2022-10-23 20:51 UTC, Toricane commented on tests/test_new_command_system.py
> +            {
Theres a lot of these

2022-10-23 20:52 UTC, EdVraz commented on tests/test_library_exception.py
> +)
"comment is outdated" you have to make a new one

2022-10-23 20:53 UTC, EdVraz commented on tests/test_new_command_system.py
> +            {
Why tho, I understand that it's nicer for the total but for the few options in total I don't think it's nessecary

2022-10-23 20:54 UTC, Toricane requested changes

2022-10-23 20:54 UTC, Toricane commented on tests/test_library_exception.py
> +    *range(10_026, 10_034),
```suggestion
    *range(10001, 10017),
    10020,
    *range(10026, 10034),
```

2022-10-23 20:54 UTC, Toricane commented on tests/test_library_exception.py
> +    *range(10_065, 10_072),
```suggestion
    *range(10065, 10072),
```

2022-10-23 20:54 UTC, Toricane commented on tests/test_library_exception.py
> +    *range(30_001, 30_006),
```suggestion
    *range(30001, 30006),
```

2022-10-23 20:55 UTC, Toricane commented on tests/test_new_command_system.py
> +            {
fine

2022-12-03 13:39 UTC, closed without merging