refactor(automod ): Add new triggers, fix create rule endpoint
interactions-py/interactions.py pull request #1154
Opened 2022-11-09 13:33 UTC by Damego

## About

This pull request is about (X), which does (Y).

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [x] For the documentation
  - [x] To add a new feature
  - [x] As a general enhancement
  - [x] As a refactor of the library/the library's code
  - [x] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-11-09 13:36 UTC, EdVraz requested changes

2022-11-09 13:36 UTC, EdVraz commented on interactions/api/models/misc.py
> +    :ivar Optional[List[int]] allow_list: Substrings which will be exempt from triggering the preset trigger type.
Strings but list of int?

2022-11-09 13:38 UTC, Damego commented on interactions/api/models/misc.py
> +    :ivar Optional[List[int]] allow_list: Substrings which will be exempt from triggering the preset trigger type.
idk why im wrote like that

2022-11-10 12:28 UTC, sillyElvy requested changes
Merge conflict

2022-11-10 12:38 UTC, Damego commented
Resolved

2022-11-10 12:51 UTC, EdVraz approved these changes

2022-11-10 12:51 UTC, merged