docs: rework the docs to showcase when specific methods have been added
interactions-py/interactions.py pull request #1161
Opened 2022-11-09 21:57 UTC by EdVraz

## About

This pull request is about (X), which does (Y).

## Checklist

- [x] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [ ] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [x] For the documentation
  - [ ] To add a new feature
  - [ ] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_context_managers.py
> +    .. versionadded:: 4.3.2
```suggestion
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_context_managers.py
> +from abc import ABC, abstractmethod
```suggestion
# versionadded declared in docs gen file
from abc import ABC, abstractmethod
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_context_managers.py
> +
```suggestion
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_iterators.py
> +from abc import ABC, ABCMeta, abstractmethod
```suggestion
# versionadded declared in docs gen file
from abc import ABC, ABCMeta, abstractmethod
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_iterators.py
> +    .. versionadded:: 4.3.2
```suggestion
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_iterators.py
> +
```suggestion
```

2022-11-22 22:17 UTC, EdVraz commented on interactions/utils/abc/base_iterators.py
> +    A base class for iterators.
```suggestion
    A base class for iterators.
```

2022-11-22 23:45 UTC, mAxYoLo01 requested changes

2022-11-22 23:45 UTC, mAxYoLo01 commented on docs/utils.abc.context_managers.rst
> +    This page contains metaclasses. As this is an advanced Python topic you should not try to use this methods
```suggestion
    This page contains metaclasses. As this is an advanced Python topic you should not try to use these methods
```

2022-11-22 23:45 UTC, mAxYoLo01 commented on docs/utils.abc.iterators.rst
> +    This page contains metaclasses. As this is an advanced Python topic you should not try to use this methods
```suggestion
    This page contains metaclasses. As this is an advanced Python topic you should not try to use these methods
```

2022-11-22 23:45 UTC, mAxYoLo01 commented on docs/utils.abc.rst
> +    This page contains metaclasses. As this is an advanced Python topic you should not try to use this methods
```suggestion
    This page contains metaclasses. As this is an advanced Python topic you should not try to use these methods
```

2022-11-25 20:38 UTC, mAxYoLo01 approved these changes

2022-11-26 01:13 UTC, Damego approved these changes

2022-11-26 01:14 UTC, merged