feat: implement modify guild emoji helper
interactions-py/interactions.py pull request #1202
Opened 2022-12-15 18:19 UTC by ItsRqtl

## About

This pull request is about (X), which does (Y).

## Checklist

- [ ] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [ ] I've ensured the change(s) work on `3.8.6` and higher.

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [x] To add a new feature
  - [ ] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [ ] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

This is:
  - [ ] A breaking change

2022-12-16 03:06 UTC, Damego requested changes

2022-12-16 03:06 UTC, Damego commented on interactions/api/models/guild.py
> +        _name = emoji.name if name is MISSING else name
No need to send original name of emoji.
Also you could get rid of `_name` variable like this
```py
if name is not MISSING:
    payload["name"] = name
```

2022-12-16 03:06 UTC, Damego commented on interactions/api/models/guild.py
> +            emoji = await self.get_emoji(int(emoji_id))
You need only ID so why you want to get emoji object?

2022-12-16 03:06 UTC, Damego commented on interactions/api/models/guild.py
> +            _roles = [role.id if isinstance(role, Role) else role for role in roles]
`_roles` variable seems like useless for me.
Also convert `Snowflake` to `int` here

2022-12-16 03:06 UTC, Damego commented on interactions/api/models/guild.py
> +            if int(item.id) == int(emoji.id):
```suggestion
            if item.id == emoji.id:
```

2022-12-16 03:06 UTC, Damego commented on interactions/api/models/guild.py
> +        Edits an Emoji in the guild.
```suggestion
        """
        .. versionadded:: 4.4.0

        Edits an emoji in the guild.
```

2022-12-16 03:24 UTC, Damego commented on interactions/api/models/guild.py
> +        _emoji = Emoji(**res)
Missed http client

2022-12-16 04:56 UTC, Damego commented on interactions/api/models/guild.py
> +            int(emoji_id)
You could just
```py
emoji_id = int(emoji_id.id if isinstance(emoji_id, Emoji) else emoji_id)
```

2022-12-16 04:56 UTC, Damego commented on interactions/api/models/guild.py
> +            payload["roles"] = [int(role.id) if isinstance(role, Role) else role for role in roles]
```suggestion
            payload["roles"] = [int(role.id if isinstance(role, Role) else role) for role in roles]
```

2022-12-16 04:56 UTC, Damego commented on interactions/api/models/guild.py
> +            if int(item.id) == emoji_id:
```suggestion
            if item.id == emoji_id:
```

2022-12-16 05:04 UTC, Damego commented
Test it please

2022-12-16 05:10 UTC, ItsRqtl commented
> Test it please

doing some work, will test it soon

2022-12-21 19:07 UTC, ItsRqtl commented
both tested and worked

2022-12-22 02:39 UTC, Damego commented on interactions/api/models/emoji.py
> +        reason: Optional[str] = MISSING,
```suggestion
        reason: Optional[str] = None,
```

2022-12-27 04:23 UTC, Damego approved these changes

2022-12-27 04:23 UTC, merged