feat: Add command enhancements
interactions-py/interactions.py pull request #1230
Opened 2023-01-20 18:38 UTC by i0bs

This proposal targets the `5.x` branch and allows commands to infer from the coroutine's name instead of requiring kwargs usage of the decorator.

Additionally, I added a `.respond()` alias to `.send()` for sending.

2023-01-21 08:17 UTC, LordOfPolls requested changes
Context Menus don't appear to work with this (even after fixing the default param issue): 
```python
@context_menu(context_type=CommandTypes.USER)
async def user_menu(ctx):
    ...
```

![image](https://user-images.githubusercontent.com/22540825/213858479-0187997e-9b5d-4a42-b3e1-ac102b662758.png)

2023-01-21 08:17 UTC, LordOfPolls commented on interactions/models/internal/application_commands.py
>      context_type: "CommandTypes",
Non-default parameter follows a default parameter

2023-01-21 13:24 UTC, i0bs commented on interactions/models/internal/application_commands.py
> +    name: Absent[str | LocalisedName] = MISSING,
```suggestion
    name: str | LocalisedName,
```

2023-01-23 08:29 UTC, LordOfPolls commented
Why have you reverted support for the nameless definition on context menus?

2023-01-25 04:16 UTC, silasary requested changes

2023-01-25 04:16 UTC, silasary commented on interactions/client/mixins/send.py
> +    async def respond(
Any reason we can't just do `respond = send`?

2023-02-02 09:04 UTC, LordOfPolls commented
Closing due to inactivity. Feel free to reopen but bare in mind:
- respond aliasing has now been integrated upstream 
- this branch is **very** out-of-sync

2023-02-02 09:04 UTC, closed without merging