feat: improve slash_option decorator
interactions-py/interactions.py pull request #1340
Opened 2023-04-11 16:45 UTC by Toricane

## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [x] Documentation update
- [x] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description

Improves the slash_option decorator so that the name, option type, and required arguments are inferred based on the parameter.
Example before and after:
```py
@slash_command(name="my_command", ...)
@slash_option(
    name="integer_option",
    description="Integer Option",
    required=True,
    opt_type=OptionType.INTEGER
)
async def my_command_function(ctx: InteractionContext, integer_option: int):
    await ctx.send(f"You input {integer_option}")
```
```py
@slash_command(name="my_command", ...)
@slash_option("Integer Option")
async def my_command_function(ctx: InteractionContext, integer_option: int):
    await ctx.send(f"You input {integer_option}")
```

## Changes

- The description of the option is required and can be passed to the decorator.
- The name of the option defaults to the name of the parameter.
- The type of the option can be specified as a type annotation to the parameter.
- Whether the option is required is inferred from the parameter's default value. If there is a default value specified, the option is not required.

## Related Issues

## Test Scenarios

Use the examples in the guide in the documentation.

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [ ] I've ensured my code works on Python `3.11.x`

## Checklist

- [ ] I've run the `pre-commit` code linter over all edited files
- [ ] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

2023-04-11 17:12 UTC, i0bs requested changes
I like inferring data for a slash command option, but there's some things I want to note:

- Changing `description` to be the first positional argument is a big breaking change, and shouldn't be changed. `name` and `description` should both respectively stay where they were originally.
- This proposal forces `description` to be filled in, while `name` does not. Seeing the internal behaviour for `@slash_command`, I don't see why we can't set at least a default value for a description.

2023-04-11 17:12 UTC, i0bs commented on interactions/models/internal/application_commands.py
>      description: str,
```suggestion
    description: Absent[str] = MISSING,
```

2023-04-11 17:12 UTC, i0bs commented on interactions/models/internal/application_commands.py
> +
```suggestion
        option_description = "No description" if description is MISSING else description

```

2023-04-11 17:12 UTC, i0bs commented on interactions/models/internal/application_commands.py
>              description=description,
```suggestion
            description=option_description,
```

2023-04-11 17:12 UTC, i0bs commented on interactions/models/internal/application_commands.py
>      description: str,
Making `description` the first pos. argument is a huge breaking change for client-facing code.

2023-05-02 20:34 UTC, LordOfPolls commented
Closing as stale

2023-05-02 20:34 UTC, closed without merging