feat: add kwargs to paginator send & reply methods
interactions-py/interactions.py pull request #1431
Opened 2023-05-30 11:02 UTC by SamNuttall

## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
Adds keyword arguments to paginator send and reply methods. 
These are then passed to the respective methods to pass-through their functionality

Example of usage - sending an ephemeral paginator: 
```
paginator = Paginator.create_from_string(bot, your_content, page_size=1000)
await paginator.send(ctx, ephemeral=True)  # <-- Added ephermal=True (other code taken from docs)
```

## Changes

- Added kwargs to paginator send & reply methods
- Updated BaseContext to InteractionContext as BaseContext does not include a send method

## Related Issues

## Test Scenarios

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [X] I've run the `pre-commit` code linter over all edited files
- [ ] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [X] I've updated / added  documentation, where applicable

2023-06-04 06:44 UTC, LordOfPolls requested changes
Reverted your typehint change. While yes, BaseContext is missing the send method, this is an issue with that object and should not be changed in this PR

Once this is changed, im happy for this to be merged

2023-06-04 06:44 UTC, LordOfPolls commented on interactions/ext/paginators.py
> +    async def send(self, ctx: InteractionContext, **kwargs) -> Message:
```suggestion
    async def send(self, ctx: BaseContext, **kwargs) -> Message:
```

2023-06-04 06:44 UTC, LordOfPolls commented on interactions/ext/paginators.py
> +    InteractionContext,
```suggestion
    BaseContext,
```

2023-06-05 08:29 UTC, SamNuttall commented
Reverted the typehint change as requested - I'll take a further look into the context types so I know in future :)

Do note that your second suggestion is now outdated as pre-commit removed the InteractionContext line, though I have fixed this via a manual commit.

2023-06-09 06:54 UTC, LordOfPolls approved these changes

2023-06-12 05:10 UTC, silasary approved these changes

2023-06-12 05:11 UTC, merged