fix: Snowflake encoding issue when msgspec is used fix
interactions-py/interactions.py pull request #1562
Opened 2023-10-16 09:49 UTC by Lacosst0

## Pull Request Type

- [ ] Feature addition
- [x] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description

This PR fixes sending StringSelectOption with CustomEmoji when msgspec is installed (used)

## Changes

- Added isinstance check to `enc_hook` in `interactions\client\utils\input_utils.py`

## Related Issues

#1561

## Test Scenarios

```py
@slash_command()
async def test(ctx: SlashContext):
    await ctx.respond(
        components=StringSelectMenu(
            StringSelectOption(label="test", value="test_value", emoji=(await ctx.guild.fetch_all_custom_emojis())[0]) # test emoji
        )
    )
```

## Python Compatibility

- [x] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [x] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

2023-10-16 10:18 UTC, LordOfPolls commented
Looks good. I'll test it tonight

2023-10-16 21:09 UTC, silasary requested changes

2023-10-16 21:09 UTC, silasary commented on interactions/client/utils/input_utils.py
>          if isinstance(obj, IntFlag):
You can pass a tuple of types to check, rather than duplicating the entire if block

2023-11-03 12:19 UTC, silasary approved these changes

2023-11-16 14:44 UTC, merged