fix: member.has_any_role working on member
interactions-py/interactions.py pull request #1620
Opened 2024-02-22 13:18 UTC by robotbabe

## Pull Request Type
- [x] Feature addition
- [x] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
This PR fixes has_any_role() not working on member object by adding it to user.py and makes it work as originally [documented](https://interactions-py.github.io/interactions.py/API%20Reference/API%20Reference/models/Internal/checks/#interactions.models.internal.checks.has_any_role).

## Changes
- Add has_any_role() to user.py

## Test Scenarios
Use has_any_role() on member object.

## Python Compatibility
- [x] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist
- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [x] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

2024-02-22 14:09 UTC, AstreaTSS commented
While I do appreciate the PR, this isn't what the documentation says. It specifically says that it's for *checks*, not for the actual user.py.

Thus, this is a feature addition, not a bug fix.

2024-02-22 14:14 UTC, AstreaTSS requested changes
You'll need to add the typing of the function to `user.pyi` too, found in the same folder.

2024-03-08 05:03 UTC, silasary approved these changes

2024-03-13 21:08 UTC, eightween commented on interactions/models/discord/user.py
> +        return any((self.has_role(to_snowflake(role)) for role in roles))
I haven't tested this PR, but the top-down control flow for `to_snowflake()` doesn't make sense here for `roles` - `Role` ultimately inherits a `SnowflakeObject` but doesn't alias to `Snowflake_Type`. Has this code been tested?

2024-03-13 21:12 UTC, AstreaTSS commented on interactions/models/discord/user.py
> +        return any((self.has_role(to_snowflake(role)) for role in roles))
`Snowflake_Type` includes `SnowflakeObject` in its union.

2024-03-13 21:13 UTC, eightween approved these changes

2024-03-30 08:02 UTC, eightween commented
PR is on track for becoming stale

2024-03-30 13:39 UTC, AstreaTSS approved these changes

2024-03-30 13:39 UTC, merged