[feat] Add CronTrigger
interactions-py/interactions.py pull request #1632
Opened 2024-03-17 05:00 UTC by zevaryx

## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description

Adds a new Task Trigger, CronTrigger. Pass a cron string to it (i.e. `0 0 * * *`), and it'll run tasks based on that cron string

## Changes

- Add `croniter` requirement
- Add `CronTrigger` task trigger

## Related Issues

## Test Scenarios

```py
@Task.create(CronTrigger("* * * * *"))
async def test_cron(self) -> None:
    print("I run every minute!")
```

## Python Compatibility

- [x] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [ ] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [x] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

2024-03-17 05:01 UTC, AstreaTSS commented
This debatably solves #1560.

2024-03-17 10:16 UTC, silasary approved these changes

2024-03-17 10:17 UTC, silasary commented
> This debatably solves https://github.com/interactions-py/interactions.py/issues/1560.

I think it does, yeah

2024-03-17 19:52 UTC, AstreaTSS requested changes

2024-03-17 19:52 UTC, AstreaTSS commented on interactions/models/internal/tasks/triggers.py
> +        utc bool: Whether or not to use UTC for the time
Seems like you forgot to change this part 😅

2024-03-30 08:10 UTC, eightween commented on interactions/models/internal/tasks/triggers.py
> +        utc bool: Whether or not to use UTC for the time
What about this needs to be changed?

2024-03-30 13:37 UTC, AstreaTSS commented on interactions/models/internal/tasks/triggers.py
> +        utc bool: Whether or not to use UTC for the time
The `utc` docstring entry needs to be replaced with a `tz` entry.

2024-03-30 21:08 UTC, AstreaTSS approved these changes
Don't know what's going on with the PR's diff, but looks fine otherwise.

2024-03-30 21:08 UTC, merged