5.14
interactions-py/interactions.py pull request #1744
Opened 2024-11-19 10:16 UTC by silasary

New release soon

But I want #1742 to be merged first.

2024-12-08 21:43 UTC, LawMixer requested changes
![image](https://github.com/user-attachments/assets/56359577-5bcc-47ce-9c5f-b9053ca56e37)

Actions have failed the following things by the way - do we safely ignore this?

2024-12-08 22:25 UTC, silasary commented
Yeah, the voice tests are unreliable and I still haven't figured out why

2024-12-08 22:27 UTC, LawMixer approved these changes
Besides those, I've tested on python3.10 and python3.11 and it works normally.

2025-01-30 16:05 UTC, LordOfPolls approved these changes
LGTM
Tested and happy. Pytest error appears to be transient

2025-01-31 07:00 UTC, merged