[v4] Implement gateway (until heartbeat)
interactions-py/interactions.py pull request #308
Opened 2021-08-20 03:30 UTC by DeltaXWizard

## About this pull request

v4's gateway implementation, nothing too much to describe other than the title
(I'm exhausted)

## Changes

(self explanatory commit, relied on threads and async)

## Checklist

- [ ] I've run the `pre_push.py` script to format and lint code.
- [ ] I've checked this pull request runs on `Python 3.6.X`.
- [ ] This fixes something in [Issues](https://github.com/eunwoo1104/discord-py-slash-command/issues).
    - Issue:
- [ ] This adds something new.
- [ ] There is/are breaking change(s).
- [ ] (If required) Relevant documentation has been updated/added.
- [ ] This is not a code change. (README, docs, etc.)

2021-08-20 03:34 UTC, goverfl0w commented
Ain't going to commit this abomination until I regain my sanity in the morning and get the heartbeats to send. I hate websockets and everything they exist for.

2021-08-20 03:42 UTC, LordOfPolls requested changes

2021-08-20 03:42 UTC, LordOfPolls commented on interactions/gateway.py
> +            while not self.closed:
This logic is broken. You recieve one event, and then loop over this event over and over. Move this while loop to wrap line 130

2021-08-21 18:40 UTC, goverfl0w commented
We've revamped the gateway logic entirely now to use a client session-invoked websocket connection, which should eliminate most problems. Gateway now functions normally and the bot stays online.

2021-08-21 18:56 UTC, goverfl0w approved these changes

2021-08-21 18:57 UTC, merged