Unstable
interactions-py/interactions.py pull request #376
Opened 2021-12-13 16:51 UTC by MeidoNoHitsuji

- generates an appropriate name for the autocomplete event
- add argument "value" of the command in the autocomplete event
- don't be afraid to cancel if you find any error :D

2021-12-13 17:39 UTC, goverfl0w requested changes
Changes to respect subcommand checking in autocompletion.

2021-12-13 17:39 UTC, goverfl0w commented on interactions/api/gateway.py
> +                                    if option["type"] == OptionType.SUB_COMMAND_GROUP:
I think we could build a submethod to make this check easier inside of the `handle_dispatch`:

```py
def check_sub_auto(option):
    if "options" in option:
        if option["type"] == OptionType.SUB_COMMAND:
            if sub_option.get("focused") for sub_option in option["options"]:
                _args.append(option["name"])
        elif option["type"] == OptionType.SUB_COMMAND_GROUP:
            if "options" in group_option for group_option in option["options"]:
                if sub_option.get("focused") for sub_option in group_option["options"]:
                    _name += sub_option["name"]
                    _args.append(sub_option["value"])
    elif option.get("focused"):
        _name += option{"name"]
        _args.append(option["value"])
```

This check will also respect the issue you have with changed line 307, where we suddenly ignore the actual group option. Black should also format all of this to respect the character line limit, so it theoretically will look better once pre-committed.

2021-12-13 17:39 UTC, goverfl0w commented on interactions/api/gateway.py
> +                                    if option["type"] == OptionType.SUB_COMMAND_GROUP:
```suggestion
                                    check_sub_auto(option)
```

2021-12-14 20:56 UTC, goverfl0w commented
Does this work with the new suggestions @MeidoNoHitsuji ?
If possible, please provide debug log.

2021-12-15 19:03 UTC, MeidoNoHitsuji commented
Yes, this work with the new suggestions
I don't know what kind of logs ur needs)
I also added the transfer of the selection of command parameters (subcommands, groups and options) to the callback..

2021-12-16 16:59 UTC, goverfl0w approved these changes
LGTM.

2021-12-16 16:59 UTC, goverfl0w commented
I'll be merging this pull request. Thank you for your contribution! Welcome to the contributors table. 😃

2021-12-16 17:00 UTC, merged