fix: component sending/editing with context
interactions-py/interactions.py pull request #396
Opened 2021-12-21 04:36 UTC by Toricane

## About

This pull request is about fixing component sending/editing with context, which lets you send/edit components using the context (`ctx`) properly.
Specifically `await ctx.send(...)` and `await ctx.edit(...)`.

In addition to fixing component sending/editing, I have also filled in missing ways to send/edit components:

### Sending/editing one ActionRow

Here is a sample code example where you can send and edit one ActionRow:
```py
await ctx.send("c", components=button_row1)
await asyncio.sleep(1)
await ctx.edit("c", components=button_row2)
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/922705605964234783/lWCDNM1W0L.gif"></img>

### Sending/editing individual components
Sample code:
```py
await ctx.send("b", components=select)
await asyncio.sleep(1)
await ctx.edit("b", components=button1)
await asyncio.sleep(1)
await ctx.edit("b", components=select)
await asyncio.sleep(1)
await ctx.send("b", components=button1)
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/922706436704862208/zv4VSpqyAh.gif"></img>

### Sending/editing multiple ActionRows
Sample code:
```py
await ctx.send("lol", components=[button_row1, button_row2])
await asyncio.sleep(1)
await ctx.edit("ayo", components=[button_row2, button_row1])
await asyncio.sleep(1)
await ctx.edit("wow", components=[select_row1, select_row2])
await asyncio.sleep(1)
await ctx.edit("ez", components=[select_row2, select_row1])
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/922706983784697856/sJekRy3X8w.gif"></img>

### Sending/editing with lists
Sample code:
```py
await ctx.send("a", components=[[button1, button2], [select]])
await asyncio.sleep(1)
await ctx.edit("a", components=[[select], [button1, button2]])
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/922707644265922560/w2qCyOYAIU.gif"></img>

### Finally, removing components
When editing, the components stay if `components=None`, but anything else that is not a list of action rows, a list of components, component, action row, or a list of a list of components (example: `[]`), the components will be removed from the message.
Sample code:
```py
await ctx.send("hi", components=button1)
await asyncio.sleep(1)
await ctx.edit("hi", components=None)
await asyncio.sleep(1)
await ctx.edit("hi", components=[])
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/922708789130579978/4niEhc445v.gif"></img>

Please review this code and tell me if I have done anything incorrectly.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [x] Bugfix

2021-12-21 19:26 UTC, goverfl0w commented
Since you've implemented mutable tables to the `components` argument for sending, can you test `interactions.ActionRow()` working alongside `[]`?

2021-12-21 19:50 UTC, Toricane commented
You mean like `[[button1], ActionRow(components=[button2])`?
Yeah I haven't implemented that, I will do it

2021-12-22 01:54 UTC, Toricane commented
Okay @goverfl0w, I have implemented it.
Code example:
```py
await ctx.send(
    "testing",
    components=[[button1, button2], interactions.ActionRow(components=[select])],
)
await asyncio.sleep(1)
await ctx.edit(
    "wow",
    components=[interactions.ActionRow(components=[select]), [button2, button]],
)
```
Result:
<img src="https://cdn.discordapp.com/attachments/922703586301972561/923030394851446864/kziNVrJeqR.gif"></img>

2021-12-28 00:05 UTC, Toricane commented
I think there may be an issue for checking if `custom_id` is in the button, the button may be a URL button. I think I can solve this by checking if there is a URL in the button *after* checking if there is a `custom_id`.

2021-12-28 00:23 UTC, Toricane commented
Yep it works, used `or component._json.get("url")`

2022-01-02 13:40 UTC, goverfl0w approved these changes

2022-01-02 13:40 UTC, i0bs commented on interactions/context.py
> +            Union[Union[ActionRow, Button, SelectMenu], List[Union[ActionRow, Button, SelectMenu]]]
`Union[Union[`
Why is union repeated twice?

2022-01-02 13:40 UTC, i0bs commented on interactions/context.py
> +                components._json["options"] = [option._json for option in components.options]
`components._json["options"]` should not need to be overwritten as of the latest `unstable` commit, since we have a recursive generator being applied.

2022-01-02 13:40 UTC, i0bs commented on interactions/context.py
> +            Union[Union[ActionRow, Button, SelectMenu], List[Union[ActionRow, Button, SelectMenu]]]
Same as `send`

2022-01-02 13:42 UTC, goverfl0w requested changes
Just noticed, this still has not been fixed: 

```py
        components: Optional[
            Union[Union[ActionRow, Button, SelectMenu], List[Union[ActionRow, Button, SelectMenu]]]
        ]
```

You have `Union` repeating twice.

2022-01-02 18:26 UTC, Toricane commented on interactions/context.py
> +            Union[Union[ActionRow, Button, SelectMenu], List[Union[ActionRow, Button, SelectMenu]]]
changed to
```py
components: Optional[
    Union[ActionRow, Button, SelectMenu, List[Union[ActionRow, Button, SelectMenu]]]
] = None,
```

2022-01-02 18:27 UTC, Toricane commented on interactions/context.py
> +            Union[Union[ActionRow, Button, SelectMenu], List[Union[ActionRow, Button, SelectMenu]]]
Changed it to:
```py
components: Optional[
    Union[ActionRow, Button, SelectMenu, List[Union[ActionRow, Button, SelectMenu]]]
] = None,
```

2022-01-02 18:28 UTC, goverfl0w approved these changes

2022-01-02 18:31 UTC, Toricane commented on interactions/context.py
> +                components._json["options"] = [option._json for option in components.options]
Removed lines 257 and 258, and the respective lines in `edit()` as well

2022-01-02 18:32 UTC, Toricane commented
I have resolved the changes, I will test them now

2022-01-02 18:42 UTC, Toricane commented on interactions/context.py
> +                components._json["options"] = [option._json for option in components.options]
Oh yeah @goverfl0w, this is why I put it in the first place:
```py
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-16' coro=<my_command() done, defined at c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\main.py:31> exception=TypeError('Object of type SelectOption is not JSON serializable')>
Traceback (most recent call last):
  File "c:\Users\hi\Desktop\Coding\Python\discord-interactions v4\main.py", line 143, in my_command
    await ctx.send("b", components=select)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 343, in send
    await func()
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\context.py", line 336, in func
    await self.client.create_interaction_response(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\http.py", line 2061, in create_interaction_response
    return await self._req.request(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\interactions\api\http.py", line 200, in request
    async with self.session.request(
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 390, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\payload.py", line 381, in __init__
    dumps(value).encode(encoding),
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\hi\AppData\Local\Programs\Python\Python39\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SelectOption is not JSON serializable
```
I'm gonna revert the commit and keep the lines and try again

2022-01-02 19:37 UTC, merged