feat: implement new functions
interactions-py/interactions.py pull request #418
Opened 2022-01-05 14:59 UTC by EdVraz

## About

This PR:
- Adds new functions:
  - Channel:
    - pin_message()
    - unpin_message()
    - publish_message()
    - get_pinned_messages()
  - Message:
    - pin()
    - unpin()
    - publish()
  - Guild:
    - get_all_channels()
    - get_all_roles()
    - modify_role_position()
    - get_bans()
  - Role:
    - modify_position()

- Adds missing `return` and `rtype` to docstrings 

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

2022-01-08 15:01 UTC, goverfl0w requested changes
I also see that you're importing specific models per iteration in a method, which can affect performance. (although it should be a very tiny amount because it'll recall upon loaded memory) Is there any reason why they're being done in the methods instead of an import in the file itself?

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/channel.py
> +        :return: message object
```suggestion
        :return: The message published
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/channel.py
> +    async def get_pinned_messages(self):
```suggestion
    async def get_pinned_messages(self) -> List[Message]:
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/channel.py
> +        :return: A list of pinned message objects.
```suggestion
        :return: A list of pinned message objects.
        :rtype: List[Message]
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.py
> +        :rtype: List[Role]
```suggestion
        :return: The roles of the guild.
        :rtype: List[Role]
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.py
> +        :rtype: List[Channel]
```suggestion
        :return: The channels of the guild.
        :rtype: List[Channel]
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.py
> +        return res
```suggestion
        return ban["user"]
```

This should be returning them in the converted object.

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.py
> +        :rtype: List[dict]
```suggestion
        :rtype: List[User]
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.py
> +    async def get_bans(self) -> List[dict]:
```suggestion
    async def get_bans(self) -> List[User]:
```

2022-01-08 15:01 UTC, i0bs commented on interactions/api/models/guild.pyi
> +    async def get_bans(self) -> List[dict]: ...
```suggestion
    async def get_bans(self) -> List[User]: ...
```

2022-01-08 15:01 UTC, goverfl0w commented on interactions/api/models/message.py
> +        await self._client.unpin_message(channel_id=int(self.channel_id), message_id=int(self.id))
```suggestion

        await self._client.unpin_message(channel_id=int(self.channel_id), message_id=int(self.id))
```

2022-01-08 15:07 UTC, EdVraz commented on interactions/api/models/guild.py
> +        return res
I don't understand why I should change that

2022-01-08 15:09 UTC, EdVraz commented
> I also see that you're importing specific models per iteration in a method, which can affect performance. (although it should be a very tiny amount because it'll recall upon loaded memory) Is there any reason why they're being done in the methods instead of an import in the file itself?

Circular import

2022-01-12 16:03 UTC, i0bs commented on interactions/api/models/guild.py
> +        return res
Every other helper method you have returns a converted model object, but you don't do it for this one. It's silly to keep it inconsistent.

2022-01-12 16:04 UTC, EdVraz commented on interactions/api/models/guild.py
> +        return res
it's a 
{reason: user}
so why should I don't include the reasons for the ban?

2022-01-12 16:04 UTC, goverfl0w commented on interactions/api/models/guild.py
> +        return res
Why not return a map then?

2022-01-12 16:07 UTC, EdVraz commented on interactions/api/models/guild.py
> +        return res
how would I do that? I never worked with map

2022-01-12 16:23 UTC, goverfl0w commented on interactions/api/models/guild.py
> +        return res
Map is just another way to say dictionary, it's a different term for other programming languages. Just return a dictionary where the key and value are mapped respectively with a User object to reason relation.

2022-01-12 16:26 UTC, EdVraz commented on interactions/api/models/guild.py
> +        return res
ok, how would I typehint that?

2022-01-12 16:34 UTC, EdVraz commented on interactions/api/models/guild.py
> +        return res
I just checked again
It's
`{"user": user, "reason": reason}`
actually

2022-01-13 21:05 UTC, DeltaXWizard approved these changes
Tested selects on this particular PR, and got no errors on the boot of this instance, and of sending selects. Looks good to me :)

2022-01-13 21:11 UTC, merged