feat: allow passing a command name in autocomplete decorator
interactions-py/interactions.py pull request #429
Opened 2022-01-13 06:28 UTC by V3ntus

## About

This allows a string to be passed (as per Delta's suggestion) and passed in a cache `get()` call

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [X] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): A comment by [@pwuertz](https://github.com/goverfl0w/discord-interactions/pull/422#issuecomment-1011518065) on #422 
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [ ] Breaking change
  - [X] New feature/enhancement
  - [ ] Bugfix

2022-01-13 21:09 UTC, DeltaXWizard requested changes

2022-01-13 21:09 UTC, DeltaXWizard commented on interactions/client.py
> +                self.synchronize()
`self.synchronize()` is a coroutine.

2022-01-13 21:23 UTC, V3ntus commented
@DeltaXWizard Oops, missed that

Is this method a good way to ensure callback functionality (calling `synchronize()` when returned None)? If the autocomplete callback is registered before its command counterpart, this would result in a failure. Is that left up to the users to be aware of?

2022-01-15 20:55 UTC, EdVraz requested changes
this are my first suggestions, sorry if it looks horrible

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
> +        else:
I'd recommend checking if it is actually an integer and if not raising an exception.

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
>              command.id if isinstance(command, ApplicationCommand) else command
```suggestion
```

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
>          _command: Union[Snowflake, int] = (
```suggestion
```

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
>          )
```suggestion
```

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
>          )
remove this, it is iterated twice and unnecessary

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
> +        else:
```suggestion
        elif isinstance(command, int):
        _command: Union[Snowflake, int] = command
```

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
> +            _command: Union[Snowflake, int] = command
```suggestion

```

2022-01-15 20:55 UTC, EdVraz commented on interactions/client.py
> +
```suggestion

else:
       raise ValueError("you provided a wrong data type! Only 'ApplicationCommand' 'str' and 'int' are allowed!")  # TODO: move to custom error formatter
       
```

2022-01-15 21:09 UTC, EdVraz requested changes
now its better lol

2022-01-15 21:09 UTC, EdVraz commented on interactions/client.py
> +
```suggestion
        elif isinstance(command, int):
            _command: Union[Snowflake, int] = command
        else:
              raise ValueError("You can only insert string, intergers and ApplicationCommands here!") # TODO: move to custom error formatter
```

2022-01-15 21:09 UTC, EdVraz commented on interactions/client.py
>          )
```suggestion
```

2022-01-15 21:10 UTC, EdVraz commented on interactions/client.py
> +
I'd recommend checking if it is actually an integer and if not raising an exception.

2022-01-15 21:10 UTC, EdVraz commented on interactions/client.py
>          )
remove it, it's a duplicate check

2022-01-16 19:55 UTC, EdVraz requested changes
Sorry one typo i made myself lol

2022-01-16 19:55 UTC, EdVraz commented on interactions/client.py
> +                "You can only insert string, intergers and ApplicationCommands here!"
```suggestion
                "You can only insert strings, integers and ApplicationCommands here!"
```
sry one typo

2022-01-17 12:23 UTC, EdVraz approved these changes
LGTM :+1:

2022-02-03 00:11 UTC, DeltaXWizard approved these changes
Looked this over, LGTM :)

2022-02-03 00:13 UTC, merged