Fix logging: default to NullHandler
interactions-py/interactions.py pull request #431
Opened 2022-01-13 21:42 UTC by V3ntus

## About

Related to #421

Unless a simple logging configuration is setup, log messages should be hidden. Users can set the level with `logging.basicConfig(level=logging.DEBUG)` ex. if they desire. This sets up a new StreamHandler for them that `interactions` should output to

A list of loggers (their names) is present in `base.Data` which gets populated after importing `interactions`

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [X] Bugfix

2022-01-13 21:57 UTC, Catalyst4222 commented
Personally, I think that Warning, Error, and Critical should be shown if it directly relates to the user

So (as examples) a duplicate command should warning/error to stderr, but the critical from missing attributes shouldn't be shown

2022-01-13 22:03 UTC, V3ntus commented
> Personally, I think that Warning, Error, and Critical should be shown if it directly relates to the user

I agree. I suppose NullHandlers would be a bad idea as default then. The missing attribute warning spam gets somewhat irritating, and confusing for some as well. Maybe we can pass errors and critical?

2022-01-13 22:14 UTC, V3ntus commented
e500293 should allow errors, but still give users the ability to define a `logging.basicConfig` with a level of their choice. This also should prevent duplicate log messages in console. 

Tested

2022-01-15 20:39 UTC, EdVraz requested changes
Except those two smaller issues this looks fine to me

2022-01-15 20:39 UTC, EdVraz commented on interactions/base.py
> +    :ivar LOGGERS List[str]: A list of all loggers registered from this library
Add the log level to the Docstring, too

2022-01-15 20:39 UTC, EdVraz commented on interactions/base.py
> +    _logger.addHandler(handler)
add `_handler`not `handler`

2022-01-15 20:55 UTC, V3ntus commented
> Except those two smaller issues this looks fine to me

Thanks, missed those two

2022-01-15 20:56 UTC, EdVraz commented
> > Except those two smaller issues this looks fine to me
> 
> Thanks, missed those two

no problem

2022-01-16 19:36 UTC, EdVraz approved these changes
LGTM 👍

2022-01-20 02:37 UTC, goverfl0w commented
I'm willing to include this as a refactor instead of a feature commit, but there's a merge conflict stopping me from doing that.

2022-01-20 13:30 UTC, V3ntus commented
Alright I'll try to get that resolved today

2022-01-20 21:04 UTC, V3ntus commented
Merged unstable, I don't see merge conflicts anymore, but let me know if there's still something wrong

2022-01-24 19:29 UTC, goverfl0w commented
Would recommend running `pre-commit` again, the checks have failed.

2022-01-24 19:40 UTC, goverfl0w commented
This PR LGTM. Thank you for contributing to the library for the first time, and welcome to the contributors club. 😃

2022-01-24 19:40 UTC, merged