feat: implement new helper methods
interactions-py/interactions.py pull request #456
Opened 2022-01-25 17:58 UTC by EdVraz

## About

This pull request implements new helper methods. It contains the changes from #455 so there shouldn't be any merge conflict with it

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

2022-02-02 06:42 UTC, goverfl0w requested changes

2022-02-02 06:42 UTC, goverfl0w commented on interactions/api/models/channel.pyi
> +class ChannelType(IntEnum):
Writing `IntEnum` metaclasses should be handled in the regular `.py` file, this is for interfacing. For `.pyi` usage, I recommend continuing to use the ellipsis type.

2022-02-02 06:42 UTC, goverfl0w commented on interactions/api/models/channel.py
> +    ) -> List:
```suggestion
    ) -> List["Message"]:
```

2022-02-02 06:42 UTC, goverfl0w commented on interactions/api/models/channel.py
> +            _allowed_time = pytz.UTC.localize(datetime.now() - timedelta(days=14))
Why are we using `pytz` as a new dependency for handling time? Is there not a datetime equivocation?

2022-02-02 06:42 UTC, goverfl0w commented on interactions/api/models/channel.py
> +    ):
```suggestion
    ) -> "Message":
```

2022-02-02 20:46 UTC, V3ntus approved these changes
LGTM

2022-02-03 19:00 UTC, V3ntus commented
Tested, working!

2022-02-03 19:01 UTC, EdVraz commented
> Tested, working!

all of them? nice! didn't remember if publishing was working

2022-02-03 19:02 UTC, V3ntus commented
> all of them? nice! didn't remember if publishing was working

![image](https://user-images.githubusercontent.com/29584664/152410867-ab65a3f6-8571-44c1-a594-2def97fe14ad.png)
Ignore failed interaction, error on my end

2022-02-03 20:44 UTC, DeltaXWizard approved these changes
LGTM :)

2022-02-03 20:45 UTC, merged