feat: implement Member.id
interactions-py/interactions.py pull request #465
Opened 2022-02-04 02:20 UTC by Toricane

## About

This pull request is about implementing `interactions.Member.id`, which lets you use `member.id` instead of `member.user.id`.
Another example is `ctx.author.id` instead of `ctx.author.user.id`.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

2022-02-04 10:26 UTC, EdVraz requested changes
This does not reflect the current api scheme, which is not including the ID into the [member object](https://discord.com/developers/docs/resources/guild#guild-member-object)

Because of this, I am against an implementation of the ID as a members attribute.

In my opinion you could add it as a property to the member class. But it's up to @goverfl0w whether he wants that property there or not.

2022-02-04 14:28 UTC, Toricane commented
Okay, I'll wait for fl0w

2022-02-04 17:43 UTC, goverfl0w commented
I agree with @EdVraz , I'd personally like to see that as a property method instead. The attributes per model are meant to really respect the API schema.

2022-02-04 17:52 UTC, Toricane commented
Ok I will change it to a property later today

2022-02-05 14:26 UTC, EdVraz approved these changes
LGTM

2022-02-05 19:29 UTC, merged