feat: fill Context's Guild and Channel when possible, or replace with MISSING
interactions-py/interactions.py pull request #466
Opened 2022-02-04 04:25 UTC by Catalyst4222

## About

This pull request checks the cache if the guild or channel is absent from the Context class. If there is no data, and the id (if it exists) is not found in cache, then the value is replaced with MISSING to signal that the data wasn't found

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

2022-02-06 01:22 UTC, DeltaXWizard approved these changes
LGTM 👍🏻

2022-02-06 01:24 UTC, goverfl0w requested changes

2022-02-06 01:24 UTC, goverfl0w commented on interactions/context.py
> +    :ivar Union[Guild, None, MISSING] guild: The guild data model.
Docstring on a sentinel value and a None return should always respect `Optional[]` typing schema.

2022-02-07 00:38 UTC, goverfl0w approved these changes

2022-02-07 00:38 UTC, goverfl0w commented
LGTM, in the future I might refactor this within the mixin proto impl.

2022-02-07 03:36 UTC, Catalyst4222 commented
About that, it's all green here
![image](https://user-images.githubusercontent.com/84055084/152720553-53d8189f-b13c-4ede-a6d9-1ec49b0c55c0.png)

2022-02-07 14:53 UTC, FayeDel commented
Thanks for contributing! Will merge :)

2022-02-07 14:53 UTC, merged