feat: Localisation support.
interactions-py/interactions.py pull request #686
Opened 2022-03-29 21:11 UTC by DeltaXWizard

## About

This mega PR:

- Implements localisation completely, with type-checking, Locale object usage support and documentation support.
- Implements 50x status checking and per-route rate-limit exhaustion on the HTTP client. This also utilises the `application/json` header correctly.
- Fixes listener/function removal for Extensions on extension reload/remove.
- Fixes the `timestamp` instantiation on the Embed object.

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [X] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - #684 
  - #665 
  - #598
  - #511 
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [ ] Breaking change
  - [X] New feature/enhancement
  - [X] Bugfix

2022-03-30 19:57 UTC, EdVraz requested changes

2022-03-30 19:57 UTC, EdVraz commented on interactions/api/models/message.py
> +
I made the `__setattr__` method to keep the `_json` the same as the attributes. Therefore, I don't like implementing a change between those two. Additionally, in my opinion, an isoformat can be but into the attribute, too. Converting to a datetime object is not that difficult for the user.

2022-03-30 19:57 UTC, EdVraz commented on interactions/client.py
> +        name_localizations: Optional[Dict[Union[str, Locale], str]] = MISSING,
Since this undergoes the same regex as a normal name, it would be convenient if `__check_command` would check for it, too.

2022-03-30 19:57 UTC, EdVraz commented on interactions/client.pyi
> +        description_localizations: Optional[Dict[str, str]] = MISSING,
```suggestion
        name_localizations: Optional[Dict[Union[str, Locale], str]] = MISSING,
        description_localizations: Optional[Dict[Union[str, Locale], str]] = MISSING,
```

2022-03-30 19:57 UTC, EdVraz commented on interactions/client.pyi
> +        name_localizations: Optional[Dict[str, str]] = MISSING,
```suggestion
        name_localizations: Optional[Dict[Union[str, Locale], str]] = MISSING,
```

2022-03-30 19:57 UTC, EdVraz commented on interactions/client.pyi
> +        name_localizations: Optional[Dict[str, str]] = MISSING,
```suggestion
        name_localizations: Optional[Dict[Union[str, Locale], str]] = MISSING,
```

2022-03-30 19:57 UTC, EdVraz commented on interactions/decor.pyi
> +    name_localizations: Optional[Dict[str, str]] = None,
```suggestion
    name_localizations: Optional[Dict[Union[str, Locale], str]] = None,
```

2022-03-30 19:57 UTC, EdVraz commented on interactions/decor.pyi
> +    description_localizations: Optional[Dict[str, str]] = None,
```suggestion
    description_localizations: Optional[Dict[Union[str, Locale], str]] = None,
```

2022-03-30 20:31 UTC, Astrea49 commented
...I like this PR in general, but it's kind of odd. Shouldn't these be broken up into separate commits? That would be *much* clearer when scrolling back through the commit history.

2022-03-30 20:32 UTC, EdVraz commented
> ...I like this PR in general, but it's kind of odd. Shouldn't these be broken up into separate commits? That would be *much* clearer when scrolling back through the commit history.

I agree on that, I was thinking the same before

2022-03-30 20:34 UTC, Astrea49 commented
> > ...I like this PR in general, but it's kind of odd. Shouldn't these be broken up into separate commits? That would be _much_ clearer when scrolling back through the commit history.
> 
> I agree on that, I was thinking the same before

Yeah, it's weird for "localization support" to have bug fixes out of all things.
It also makes it harder to review and test.
(Also, yeah, I did mean separate PRs haha 😅.)

2022-04-02 22:35 UTC, DeltaXWizard commented
> Yeah, it's weird for "localization support" to have bug fixes out of all things.
It also makes it harder to review and test.
(Also, yeah, I did mean separate PRs haha 😅.)

Yeah this PR wasn't meant to be squashed, rather merged/rebased. (But also, I wasn't sure what else to title it 🤷🏻‍♀️)

2022-04-02 22:59 UTC, Astrea49 commented
> > Yeah, it's weird for "localization support" to have bug fixes out of all things.
> It also makes it harder to review and test.
> (Also, yeah, I did mean separate PRs haha 😅.)
> 
> Yeah this PR wasn't meant to be squashed, rather merged/rebased. (But also, I wasn't sure what else to title it 🤷🏻‍♀️)
> 
> 

That's fine and all... but this should _really_ be separated regardless of the merge strategy. It's near impossible to test everything and ensure everything is working fine, and also makes digging through PRs to find what is introduced harder.

IMO there's absolutely no reason this _shouldn't_ be closed and separated into various PRs.

2022-04-02 23:15 UTC, EdVraz approved these changes
Seems to look good, I can't see anything bad in the latest commits

2022-04-02 23:38 UTC, merged