fix: Fix remaining variable definition.
interactions-py/interactions.py pull request #696
Opened 2022-04-02 23:45 UTC by DeltaXWizard

## About

This bug fix simply rechecks if the `remaining` variable is None.

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [X] Bugfix

2022-04-02 23:47 UTC, goverfl0w requested changes
Use `and` operation

2022-04-03 14:21 UTC, EdVraz approved these changes

2022-04-03 14:22 UTC, EdVraz commented
@goverfl0w has to approve since he requested changes

2022-04-03 14:24 UTC, goverfl0w commented
All good now, force merge if needed since github mobile is being a cock. 

(Request review from me Austin next time too please!)

2022-04-03 19:06 UTC, goverfl0w approved these changes

2022-04-03 19:06 UTC, merged