docs, feat: Implement barebones Forum channel support.
interactions-py/interactions.py pull request #766
Opened 2022-04-28 01:44 UTC by DeltaXWizard

## About

This PR title essentially explains itself.
Forums are in testing but has been more widespread, so this is left as a draft PR until its live/more features are discovered.

This correlates to an earlier PR: #630 

## Checklist

- [X] I've ran `pre-commit` to format and lint the change(s) made.
- [X] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [X] I've made this pull request for/as: (check all that apply)
  - [X] Documentation
  - [ ] Breaking change
  - [X] New feature/enhancement
  - [ ] Bugfix

2022-07-11 01:59 UTC, ffl0w commented
As of 5 July.

![image](https://user-images.githubusercontent.com/41456914/178174621-7850b17e-445b-48ed-9152-2913de85cb5e.png)

2022-07-25 16:50 UTC, EdVraz commented on interactions/api/models/channel.py
> +        this object exists moreso for future helper methods.
Wouldn't it make more sense to keep the methods on the channel object like we did for threads?

2022-09-14 16:29 UTC, DeltaXWizard commented
Forums are officially out so I'm marking this as ready for review ^^

2022-09-14 16:33 UTC, EdVraz requested changes

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/channel.py
> +    # )
_uh_

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/channel.py
> +    # self.presence = Presence(**self._json.get("presence")) if self._json.get("presence") else None
Will you do something with this or just let it exist?

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/channel.py
> +    # )
_uh_

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/channel.py
> +    ...
_uh_

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/channel.py
> +        this object exists moreso for future helper methods.
Helpers are generally implemented in the base channel class so people don't have to use different objects for different channels - if this is not needed, it should be removed

2022-09-14 16:33 UTC, EdVraz commented on interactions/api/models/gw.py
> +# More prevalent on forums for some odd reason.
If its forum related why not add it?

2022-09-14 16:34 UTC, EdVraz commented
Docs build failed

2022-09-14 21:55 UTC, EdVraz approved these changes
Lgtm!

2022-09-14 21:58 UTC, merged