feat: Add support for GET invite endpoint
interactions-py/interactions.py pull request #804
Opened 2022-05-27 15:09 UTC by Nanrech

## About

This pull request adds support for the GET invite endpoint and moves the DELETE invite one to a new class, InviteRequest, from ChannelRequest.

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - #803 
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [x] New feature/enhancement
  - [ ] Bugfix

2022-05-31 20:58 UTC, EdVraz requested changes
Resolve the ci failure please

2022-05-31 20:58 UTC, EdVraz commented on interactions/api/http/invite.py
> +
```suggestion
__all__ = ["InviteRequest"] 


```

2022-05-31 20:58 UTC, EdVraz commented on interactions/api/models/guild.py
> +        )
```suggestion
        self.guild_scheduled_event = ( ScheduledEvents(
            **self._json.get("guild_scheduled_event"))
            if isinstance(self._json.get("guild_scheduled_event") , dict)
            else self._json.get("guild_scheduled_event")
        )
```

2022-06-01 06:44 UTC, Nanrech commented
pre-commit.ci autofix

2022-06-01 06:45 UTC, sillyElvy commented
> pre-commit.ci autofix

https://results.pre-commit.ci/run/github/320551108/1654065877.uzBWBZ6wQuSZfWQ_YYNhuw

2022-06-01 07:07 UTC, Nanrech commented
Ok, it should be good to go now.

2022-06-01 07:08 UTC, EdVraz approved these changes

2022-06-01 07:08 UTC, merged