docs: Update faq.rst
interactions-py/interactions.py pull request #878
Opened 2022-06-23 18:00 UTC by EdVraz

## About

This PR updates the faq

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

2022-06-25 02:35 UTC, Toricane requested changes
Some grammar suggestions
Also why are there deleted sections? That's not related to this PR

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +- `enhanced`_ what enhances the DX in general
```suggestion
- `enhanced`_ which enhances the DX in general
```

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +Please join our `Discord server`_ for any further support regarding our library and/or any integration code depending on it.
```suggestion
Please join our `Discord Server`_ for any further support regarding our library and/or any integration code depending on it.
```
Consistency

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +    comments, feedback or concerns please consider joining our `Discord Server`_
```suggestion
    comments, feedback or concerns, please consider joining our `Discord Server`_
```

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +internal development feel free to ask in the discord support server.
```suggestion
internal development, feel free to ask in the Discord support server.
```

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +The current state of discord.py and its further development is very unclear. What about your lib?
```suggestion
The current state of discord.py and its further development is unclear. What about your library?
```

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +Below are a few not yet officially supported exts what allowing some functional that are similar to what d.py had:
```suggestion
Below are a few unofficial exts (for the time being) which implement some functionality similar to what d.py had:
```

2022-06-25 02:35 UTC, Toricane commented on docs/faq.rst
> +Yeah you can! We have a special channel reserved for the development of external libraries!
```suggestion
Yeah, you can! We have a special channel reserved for the development of external libraries!
```

2022-06-25 07:41 UTC, EdVraz commented
> Some grammar suggestions
> Also why are there deleted sections? That's not related to this PR 

This PR is about to update the FAQ section. So it is definitely related imo. I deleted those sections since they origin from way before when Danny announced his end of development, but I don't feel like those questions are *Frequently Asked* anymore



Ok before sending this comment I saw wym, I have to merge unstable into my branch ig

2022-06-25 14:13 UTC, EdVraz commented
> > Some grammar suggestions
> > Also why are there deleted sections? That's not related to this PR
> 
> This PR is about to update the FAQ section. So it is definitely related imo. I deleted those sections since they origin from way before when Danny announced his end of development, but I don't feel like those questions are _Frequently Asked_ anymore
> 
> Ok before sending this comment I saw wym, I have to merge unstable into my branch ig

Ok on gh in the browser there are actually no deleted sections outside the faq lol

2022-06-26 18:31 UTC, Toricane approved these changes
LGTM!

2022-06-26 18:31 UTC, merged