docs: Add page describing how to use events
interactions-py/interactions.py pull request #879
Opened 2022-06-24 19:44 UTC by EdVraz

## About

This pull request is about (X), which does (Y).

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

2022-06-28 13:26 UTC, Jimmy-Blue approved these changes
Approved!

2022-06-28 15:22 UTC, Toricane requested changes, later dismissed
Grammar suggestions
Pls also replace any "discord" with "Discord" if i missed any

2022-06-28 15:22 UTC, Toricane commented on docs/events.rst
> +There is a lot of events dispatched by the Discord API. All of those can be found `here`_.
```suggestion
There are a lot of events dispatched by the Discord API. All of those can be found `here`_.
```

2022-06-28 15:22 UTC, Toricane commented on docs/events.rst
> +bot. This page will lead you through all dispatched internal events and a few from discord.
```suggestion
You all probably already know that there are several events, internal and from Discord, that you can receive with your
bot. This page will lead you through all dispatched internal events and a few from Discord.
```

2022-06-28 15:22 UTC, Toricane commented on docs/events.rst
> +Lets now have a look on those events in detail:
```suggestion
Let's now have a look on those events in detail:
```

2022-06-28 15:22 UTC, Toricane commented on docs/events.rst
> +Lets now have a look at a few events:
```suggestion
Let's now have a look at a few events:
```

2022-06-28 15:22 UTC, Toricane commented on docs/events.rst
> +This event fires whenever ``READY`` is dispatched by discord. This happens when connecting to the web socket server.
```suggestion
This event fires whenever ``READY`` is dispatched by Discord. This happens when connecting to the web socket server.
```

2022-07-04 17:09 UTC, ffl0w approved these changes

2022-07-04 17:10 UTC, ffl0w commented
Marking Toricane's review for dismissal as stale content

2022-07-04 17:10 UTC, merged